### ISSUE TITLE
Problems with RSS feed

### ISSUE THREAD

**Issue by handlerug** [maximevaillancourt/maximevaillancourt.com#10]
Hi, I'm a subscriber of your blog via RSS. Recently the feed started outputting tags such as doctype and <html> tag, and my RSS reader is unable to parse it anymore:

![Screenshot_20210310_135135](https://user-images.githubusercontent.com/24986597/110588550-bfa95800-81a7-11eb-98ae-080d79f6606a.jpg)

JSON feed works fine but I hope the RSS one will be fixed too, because JSON feeds are not as common as RSS and Atom feeds. I'm also surprised it hadn't been reported yet.

**Comment by maximevaillancourt** [comment]
Thank you so much for reporting this! :heart: 

I introduced this bug in https://github.com/maximevaillancourt/maximevaillancourt.com/commit/1b72374b7b08a75cfea098bc93723fe00d4def04.

I just fixed it in https://github.com/maximevaillancourt/maximevaillancourt.com/commit/471d4a2431abc8f50cf111ed940c2b7b1665a716.

Cheers!
